image: node:latest

stages:
  - build
  - run

# Job's name
first-job:
  # Define stage
  stage: build
  # What to run on the job.
  script:
    - npm install
  artifacts:
    paths:
      - Aula_01/node_modules

second-job:
  stage: run
  script:
    - cd Aula_01
    - npm run start
    - node test.js
  artifacts:
    paths:
      - node_modules/

